### PR TITLE
Rspec test

### PR DESCRIPTION
**Pull request by christianotieno**

### CODE REVIEW

**Review by whiz25 — APPROVED** [review]
## Good job :clap: 
All your tests have passed so it's a :+1: from me.
However, it's described [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/) that the tests are supposed to be for both OOP and the enumerable methods. May I know why you only have for OOP?

### Martin Afani

**Comment by mikenath223** [comment]
Hi please can we get further clarification on that because they both exist on different repo. Because i think perhaps we just do the enumerables test after this since they are on different repos. Please clarify

**Comment by whiz25** [comment]
It's ok @mikenath223 . I just learnt that they are different projects.

**Comment by mikenath223** [comment]
Alright. Thanks

**Pull request merged**
